server:
  port: 1011

spring:
  data:
    mongodb:
      host: localhost
      port: 27021
      username: bilgeUser
      password: bilgeUser*
      database: userdb
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: root